# Generated by Django 5.1.4 on 2024-12-11 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_barberservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagem do serviço'),
        ),
    ]
