# Generated by Django 5.1.4 on 2024-12-12 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_barberservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservice',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Duração (minutos)'),
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='image',
            field=models.ImageField(blank=True, default='services/default.jpg', null=True, upload_to='services/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagem do serviço'),
        ),
    ]
