# Generated by Django 5.1.4 on 2024-12-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_barberservice_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('manager', 'Gerente'), ('employee', 'Funcionário'), ('client', 'Cliente')], default='client', max_length=20),
        ),
    ]
