# Generated by Django 5.1.4 on 2024-12-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'Alto escalão'), ('manager', 'Gerente'), ('employee', 'Funcionário'), ('client', 'Cliente')], default='client', max_length=20),
        ),
    ]
