# Generated by Django 5.1.4 on 2024-12-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Sobrenome'),
        ),
    ]
