# Generated by Django 5.1.4 on 2024-12-15 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(help_text='O agendamento deve ser feito durante o horário comercial (07: 00 - 17: 00)', verbose_name='Data e hora do agendamento')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('canceled', 'Cancelado'), ('completed', 'Concluído')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o agendamento', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_event_id', models.CharField(blank=True, default='djangodevelopment4@gmail.com', max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.barberservice', verbose_name='Serviço')),
            ],
        ),
    ]
