# Generated by Django 5.1.4 on 2024-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_scheduling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
